[package]

name = "layers"
version = "0.1.0"
authors = ["The Servo Project Developers"]

[dependencies]
libc = "*"
rustc-serialize = "*"
log = "*"
gleam = "0.1"
euclid = "0.1"

[dependencies.skia]
git = "https://github.com/servo/skia"

[dependencies.azure]
git = "https://github.com/servo/rust-azure"

[target.x86_64-apple-darwin.dependencies]
core-foundation = "*"
cgl = "0.1"

[target.x86_64-apple-darwin.dependencies.io-surface]
git = "https://github.com/servo/io-surface-rs"

[target.i686-unknown-linux-gnu.dependencies.x11]
version = "1.1.1"
features = ["xlib"]

[target.x86_64-unknown-linux-gnu.dependencies.x11]
version = "1.1.1"
features = ["xlib"]

[target.arm-unknown-linux-gnueabihf.dependencies.x11]
version = "1.1.1"
features = ["xlib"]

[target.i686-unknown-linux-gnu.dependencies.glx]
git = "https://github.com/servo/rust-glx"

[target.x86_64-unknown-linux-gnu.dependencies.glx]
git = "https://github.com/servo/rust-glx"

[target.arm-unknown-linux-gnueabihf.dependencies.glx]
git = "https://github.com/servo/rust-glx"

[target.arm-linux-androideabi.dependencies.egl]
git = "https://github.com/servo/rust-egl"
